salesforce-url: https://developer.salesforce.com/docs/marketing/marketing-cloud/references/
locators-to-await: []
base-url: /docs/marketing/marketing-cloud/references/
initial-card: mc_rest_address
max-steps: 20