"""Type Stubs for parsing.py."""

from playwright.async_api import Locator, Page
from unstructured.documents.elements import Element

def element_to_text(element: Element) -> str: ...
async def get_all_navlinks_available(page: Page) -> list[str]: ...
async def get_main_content(page: Page) -> str: ...
def filter_missing_navlinks(navlinks: list[str]) -> list[str]: ...
async def click_all_locators(page: Page, locators: list[Locator]) -> None: ...
async def get_all_urls(page: Page, prefix: str = "") -> list[str | None]: ...
async def get_empty_navlinks_locators(
    page: Page, navlinks: list[str]
) -> list[list[Locator]]: ...
def trim_url(url: str, redundant_part: str) -> str: ...
def filter_urls_based_on_base_url(urls: list[str], base_url: str) -> list[str]: ...
